version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '${BACKEND_PORT}:8000'
    env_file:
      - ./.env
    command: npm start

  frontend:
    build:
      context: ./lingo-frontend
      dockerfile: Dockerfile
    ports:
      - '${FRONTEND_PORT}:80'
    env_file:
      - ./.env
    command: npm run build
