version: '3'
services:
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '5001:5001'
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend-dev:
    build:
      context: ./lingo-frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - ./lingo-frontend:/app
      - /app/node_modules
    command: npm run dev
