version: '3'
services:
  backend-prod:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    env_file:
      - .env
    command: npm start

  frontend-prod:
    build:
      context: ./lingo-frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    command: npm run build
