version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - '8001:${BACKEND_PORT}'
    env_file:
      - ./.env.dev
    command: npm run dev

  frontend:
    build:
      context: ./lingo-frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./lingo-frontend:/app
      - /app/node_modules
    ports:
      - '3001:${FRONTEND_PORT}'
    env_file:
      - ./.env.dev
    command: npm run dev
