version: '3'

services:
  frontend:
    build:
      context: ./lingo-frontend
      dockerfile: Dockerfile
    ports:
      - "3037:3037"
    environment:
      - VITE_BACKEND_URL=https://api.dev.lingo-cards.tech
    networks:
      - lingo-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3038:3038"
    environment:
      - ALLOWED_ORIGINS=https://dev.lingo-cards.tech,https://api.dev.lingo-cards.tech
    networks:
      - lingo-network

networks:
  lingo-network:
