version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - ./.env.prod
    command: npm start
  frontend:
    build:
      context: ./lingo-frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    env_file:
      - ./.env.prod
    command: npm run build
