name: CD Pipeline 

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/lingo-cards
            git fetch origin main
            git checkout main
            git pull origin main

            cd backend
            npm install
            pm2 restart backend-lab7 || pm2 start index.js --name backend-lab7

            cd ../lingo-frontend
            npm install
            pm2 restart frontend-lab7 || pm2 start npm --name frontend-lab7 -- run dev