name: CI Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          cd backend && npm install
          cd ../lingo-frontend && npm install

      - name: Run lint
        run: |
          cd backend && npm run lint
          cd ../lingo-frontend && npm run lint

      - name: Format code
        run: |
          cd backend && npm run format -- --check
          cd ../lingo-frontend && npm run format -- --check

      - name: Audit dependencies
        run: npm audit --production --audit-level=moderate
