name: CI Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            backend/node_modules
            lingo-frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          cd backend && npm install
          cd ../lingo-frontend && npm install

      - name: Run lint
        run: |
          cd backend && npm run lint
          cd ../lingo-frontend && npm run lint

      - name: Format code
        run: |
          cd backend && npm run format -- --check
          cd ../lingo-frontend && npm run format -- --check

      - name: Audit dependencies
        run: npm audit --production --audit-level=moderate
