name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/lingo-cards
            git fetch --all
            git reset --hard origin/${{ github.ref_name }}
            # Запуск соответствующих сервисов в зависимости от ветки
            if [ "${{ github.ref }}" == "refs/heads/main" ]; then
              docker-compose up -d --build frontend-prod backend-prod
            elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
              docker-compose up -d --build frontend-dev backend-dev
            fi
