name: Deploy to Server

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: ${{ secrets.SERVER_HOST }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            cd /home/lingo-cards

            git rev-parse --abbrev-ref HEAD

            git fetch origin
            git reset --hard origin/${{ github.ref_name }}

            export $(cat .env | xargs)

            if [ "${{ github.ref_name }}" == "main" ]; then
              docker-compose up -d --build frontend-prod backend-prod
            elif [ "${{ github.ref_name }}" == "dev" ]; then
              docker-compose up -d --build frontend-dev backend-dev
            fi
