name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            if [ '${{ github.ref }}' == 'refs/heads/main' ]; then
              DEPLOY_ENV=prod
              COMPOSE_FILE=docker-compose.prod.yml
            else
              DEPLOY_ENV=dev
              COMPOSE_FILE=docker-compose.dev.yml
            fi
            cd /root/lingo-cards
            git fetch --all
            git reset --hard origin/${{ github.ref_name }}
            docker-compose -f $COMPOSE_FILE pull
            docker-compose -f $COMPOSE_FILE up -d --build
